### ISSUE TITLE
Use your .gitignore

### ISSUE THREAD

**Issue by wtbarnes** [rescu/brainstorm#3]
Add *.ipynb (don't need these in the repo) and matplotlibrc (so that everyone's plot styles don't change) to your gitignore.........Joe.........

**Comment by joewhalen** [comment]
Teehee

**Comment by wtbarnes** [comment]
Though now that I think about it, ignoring your *rc file won't change this. If you run a notebook, the plots style according to your rc. Then when you push, they all get changed. I don't know what a good fix for that is. Maybe we should just have an rc file common to the repo so that the styling isn't always changing. Probably the best way to do it.
